name: 🚀 CD

on:
  push:
    branches: [main]

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔨 Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: 🚢 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: javiertc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🚀 Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: javiertc/steam-workshop-stats-api:latest
