name: 🚀 CD

on:
  push:
    branches: [main]

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📘 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x.x

      - name: 🔄 Restore dependencies
        run: dotnet restore

      - name: 🔨 Build Project
        run: dotnet build --no-restore

      - name: 🔎 SonarCloud Scan
        uses: highbyte/sonarscan-dotnet@v2.4.2
        with:
          sonarProjectKey: thejaviertc_sws-api
          sonarProjectName: thejaviertc_sws-api
          sonarOrganization: thejaviertc
          sonarBeginArguments: /d:sonar.qualitygate.wait=false
          dotnetDisableTests: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 🔨 Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: 🚢 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: javiertc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🚀 Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: javiertc/steam-workshop-stats-api:latest
